### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by ajkerrigan**
These updates are based on some Slack discussion. There may be other/better ways to convey this information to new contributors, so other suggestions are welcome. This is just one idea :).

### CODE REVIEW

**Comment by pogross** [comment]
Good idea to give some directions where to find stuff. However, I think the big screenshots are a bit over the top. 

Maybe provide a link + directions (slack->settings->...) and smaller screenshot of the required field only.

I can also take a look at the contributor description and provide some more details how to setup stuff.

**Comment by ajkerrigan** [comment]
That makes sense. Here's another take with less detail. I deleted the screenshots since they're only useful to show some surrounding context. For highlighting a specific field text works just as well or better.

If you're considering updates to the contributor description, the changes here are probably redundant. In that case maybe it makes more sense to close this and keep the readme simple. Your call of course - either way seems reasonable.

**Comment by bbelderbos** [comment]
Thanks @ajkerrigan, @pogross merge this in or are you move some of this into setup instructions?

**Comment by pogross** [comment]
Can be merged for now. I will take another look later in a separate PR. Maybe its better to use the docker infos to contributor section as it has no direct relation to the config file description.

**Pull request merged**
