### PR TITLE
Improve joke command

### PR DESCRIPTION
**Pull request by pmayd**
Two small changes/improvements as proposed by #37:
- get list of categories from `pyjokes.jokes_en.jokes_en dictionary` 
- use `difflib` to find closest match between user input and joke category

### CODE REVIEW

**Comment by bbelderbos** [comment]
@pmayd cool, looks good, thanks. 
Maybe add some tests around the pyjoke / `difflib` change?

**Comment by pmayd** [comment]
absolutely, will add some!

**Comment by pmayd** [comment]
Tests added, I refactored the logic into its own helper function that was easy to test with pytest -> and of course I found a stupid error ;) So now it should be more or less failsafe

**Comment by pogross** [comment]
LGTM 👍

**Comment by bbelderbos** [comment]
HardCaringHapuka-size_restricted

**Pull request merged**
