### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by clamytoe**
Minor sentence structure change. 

This sentence didn't make much sense: _However, you need to some setup and supply some settings prior to this._, so I added **do** to make it flow better.

### CODE REVIEW

**Review by bbelderbos — APPROVED** [review]
Thanks

**Comment by bbelderbos** [comment]
Working on CI issue: https://github.com/PyBites-Open-Source/karmabot/issues/107

**Comment by pogross** [comment]
@clamytoe  can you resubmit this on https://github.com/PyBites-Open-Source/karmabot/tree/develop?
Will be easier than doing merge ping pong to get this working here ;)

**Comment by clamytoe** [comment]
Sorry, been out of the loop.

**Pull request closed without merging**
