### PR TITLE
add error handling to env vars

### PR DESCRIPTION
**Pull request by pmayd**
I found it confusing that the env vars are not checked and lead to non obvious errors like failed data connection because of "NoneType" error. So I added a helper function to parse env vars and inform the user if the expected env var is missing or if it is found but empty. This improves error handling and helps the user understand where the env vars are needed and how to fix errors.

First small contribution.

### CODE REVIEW

**Comment by bbelderbos** [comment]
Nice. So do I merge this one first, then you merge forward pmayd:improve_joke_command so this change is not visible there anymore @pmayd ?

**Comment by pmayd** [comment]
I don't think so, PR are indepent of each other. So if you merge this one the second will no longer be mergeable without conflicts if the same file is targeted. Otherwise github should merge both without problems because when you merge the second PR, it will be compared with the current code base which then already contains the first PR.

However, as we have discussed I will add tests to the joke PR so I can also update from the dev branch of there are recent changes/updatrs

**Comment by pogross** [comment]
If #43 is good to go merge it and @pmayd can pull from upstream to include all the changes in #45

**Comment by bbelderbos** [comment]
Yep sounds good, thanks

**Comment by pogross** [comment]
This broke the tests. Why did CI not catch this?

**Comment by pmayd** [comment]
Hm really? Running pytest locally did not fail, so it's something with the github runners?

**Comment by pmayd** [comment]
Hm I see the envs are defined in the noxfile so why does the test say it is not available?

**Comment by pmayd** [comment]
OK because database is missing from the vars... Getting late here. So I assume before my pr the database env was empty but no test uses the dB connection so it was no deal but now it is looking for the env so I fix the nox config file with a dummy entry

**Comment by pogross** [comment]
pytest fails too, locally

```bash
❯ pytest
============================================================================================== test session starts ==============================================================================================
platform linux -- Python 3.7.9, pytest-5.4.2, py-1.9.0, pluggy-0.13.1
rootdir: /home/patrick/workspace/karmabot
plugins: mock-3.2.0, cov-2.10.0
collected 0 items / 1 error

==================================================================================================== ERRORS =====================================================================================================
____________________________________________________________________________________ ERROR collecting tests/test_karmabot.py ____________________________________________________________________________________
tests/test_karmabot.py:10: in <module>
    import karmabot.commands.topchannels
src/karmabot/commands/topchannels.py:12: in <module>
    from karmabot.settings import SLACK_CLIENT
src/karmabot/settings.py:33: in <module>
    KARMABOT_ID = _get_env_var("KARMABOT_SLACK_USER")
src/karmabot/settings.py:16: in _get_env_var
    f"{env_var} was not found. Please check your .karmabot file as well as the README.md."
E   KeyError: 'KARMABOT_SLACK_USER was not found. Please check your .karmabot file as well as the README.md.'
------------------------------------------------------------------------------------------------ Captured stderr ------------------------------------------------------------------------------------------------
09-08 22:30 root         INFO     Script started
============================================================================================ short test summary info ============================================================================================
ERROR tests/test_karmabot.py - KeyError: 'KARMABOT_SLACK_USER was not found. Please check your .karmabot file as well as the README.md.'
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
=============================================================================================== 1 error in 0.25s ================================================================================================
```

**Pull request merged**
